### ISSUE TITLE
Incompatible with other process_view middleware?

### ISSUE THREAD

**Issue by ryneeverett** [tomchristie/django-pdb#30]
Breakpoints never seem to be hit when another middleware class returns a response, which makes sense given [the docs](https://docs.djangoproject.com/en/1.8/topics/http/middleware/#process-view):

> If it returns an HttpResponse object, Django won’t bother calling any other view or exception middleware, or the appropriate view

Is this a known limitation?

**Comment by tomchristie** [comment]
Don't know, sorry. Not actively using this project myself anymore.
