### ISSUE TITLE
Deprecation warning of removal of django's unittest module from django 1.9 

### ISSUE THREAD

**Issue by Sentient07** [tomchristie/django-pdb#33]
I get the following deprecation warning while using Django 1.8 , 
django.utils.unittest will be removed in Django 1.9

**Comment by seddonym** [comment]
I've created a pull request for this, and the issue with importlib, here: https://github.com/tomchristie/django-pdb/pull/34

**Comment by tomchristie** [comment]
Close via #34. Thanks @seddonym and apologies for the long delay!
