### ISSUE TITLE
Fork guidance

### ISSUE THREAD

**Issue by 0atman** [tomchristie/django-pdb#35]
Hi Tom (and co),

I've forked this project to 
https://github.com/0atman/django-pdb-pudb
And done little more than `s/pdb/pudb`

I wanted to reach out to you and the community to make sure I'm doing the right thing with attribution, I've not done much to add value to the code!
I've also dropped it on PyPi for convenience. https://pypi.python.org/pypi/django-pdb-pudb

I've been using django-pdb for a while, and I'm really please to integrate my new favourite tool, pudb! Thanks for your help guys :-)

**Comment by tomchristie** [comment]
> I wanted to reach out to you and the community to make sure I'm doing the right thing with attribution,

That's fine as it is, yup. :)

If you wanted to add a link in the README then we could consider that (we'd also include django-extras)

**Comment by 0atman** [comment]
Add a link to your readme? I can hit you with a PR.
